[IMG-2137] Mapping script handling with super class of TimeSeriesDslL…
powsybl/powsybl-metrix pull request #103
Opened 2023-10-27 12:10 UTC by marifunf

…oader

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Possibility of loading mapping script with a super class of TimeSeriesDslLoader

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-10-30 13:30 UTC, rolnico requested changes
Logic is ok, however tests are needed for the code coverage (at least 80% is now mandatory and the more the better)

2023-11-10 16:08 UTC, rolnico approved these changes

2023-11-10 16:09 UTC, rolnico commented
Coverage is at [64.7% Coverage](https://sonarcloud.io/component_measures?id=com.powsybl%3Apowsybl-metrix&pullRequest=103&metric=new_coverage&view=list) probably due to groovy compiler optimisations.

2023-11-10 16:11 UTC, BrunoRte approved these changes

2023-11-10 16:15 UTC, merged