Mfu/img 2265
powsybl/powsybl-metrix pull request #128
Opened 2024-02-06 08:35 UTC by marifunf

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-02-06 15:46 UTC, rolnico requested changes

2024-02-06 15:46 UTC, rolnico commented on metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixChunk.java
> +                                }).collect(Collectors.toList());
I would have escaped the parenthesis (and other problematic characters) instead
```suggestion
                                List<Path> files = paths.filter(path -> path.getFileName().toString().matches(Pattern.quote(network.getId()) + "(.*)\\.xiidm")).collect(Collectors.toList());
```

2024-02-06 15:47 UTC, rolnico commented on metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixChunk.java
> +                                }).collect(Collectors.toList());
(a new import of Pattern might be needed)

2024-02-08 08:41 UTC, marifunf reviewed
ok for the suggestion

2024-02-08 10:39 UTC, merged