not versioned time series
powsybl/powsybl-metrix pull request #130
Opened 2024-03-05 14:28 UTC by marifunf

**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
No

**What kind of change does this PR introduce?**
Feature

**What is the current behavior?**

When time series are the same for several versions, it is necessary to duplicate them for each version in the csv file which must be imported

**What is the new behavior (if this is a feature change)?**
The not versioned time series can be imported as version 0

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-03-12 11:53 UTC, rolnico requested changes
Also, I'm opening a PR on powsybl-core (https://github.com/powsybl/powsybl-core/pull/2925) in order to facilitate the management of unversioned timeseries

2024-03-18 16:14 UTC, marifunf commented on metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/TimeSeriesStoreUtil.java
> +
done for isNotVersioned
getStoredVersion and removeNotVersioned are removed from here (not usefull for powsybl-metrix scope)
getTimeSeriesStoredVersion is moved to InMemoryTimeSeriesStore

2024-03-18 16:14 UTC, marifunf commented on metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/InMemoryTimeSeriesStoreTest.java
> +        assertEquals(1, getTimeSeriesStoredVersion(store, "ts1", 1));
tests are removed (tested functions are removed or moved)

2024-04-04 15:07 UTC, rolnico approved these changes

2024-04-04 15:11 UTC, merged