Fix importTimeSeries method in FileSystemTimeseriesStore
powsybl/powsybl-metrix pull request #139
Opened 2024-04-10 09:18 UTC by rolnico

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
No

**What kind of change does this PR introduce?**
Bug fix

**What is the current behavior?**
The current `importTimeSeries` method takes two booleans as parameters: `overwriteExisting` and `append`. However, an existing file cannot be overwritten (overwriteExisting` is only used with `append` to throw an exception when both booleans are false and a file already exists).

There is also no check that `overwriteExisting` and `append` cannot be true at the same time.

When a file already exists and `append` is true, the TimeSeriesIndex was not updated so only part of the chunks could be evaluated.
The chunks added were also not given an offset.

**What is the new behavior (if this is a feature change)?**
The method `importTimeSeries` now takes an enum `ExistingFiles` that can take the following values: `KEEP_EXISTING`, `OVERWRITE`, and `APPEND` instead of the booleans.
Checks were added for consistency and TimeSeries appending is now properly done.

**Does this PR introduce a breaking change or deprecate an API?**
- [x] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [x] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

The method `importTimeSeries(List, int, boolean, boolean)` is now deprecated. You should instead use `importTimeSeries(List, int, ExistingFiles)`.

2024-04-10 13:07 UTC, olperr1 requested changes

2024-04-11 06:25 UTC, rolnico commented on metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStore.java
> +        KEEP_EXISTING,
done

2024-04-11 06:52 UTC, rolnico commented on metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStore.java
> +            if (existingFiles == ExistingFiles.APPEND) {
done

2024-04-11 06:56 UTC, rolnico commented on metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStore.java
> +                        .stream(newIndex)
good point, fixed it

2024-04-11 07:02 UTC, rolnico commented on metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStore.java
> +            .toMillis() == regularExistingTimeSeriesIndex.getSpacing()
done

2024-04-11 07:08 UTC, rolnico commented on metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStore.java
> +                    existingIndex.stream().map(Instant::toEpochMilli).mapToLong(Long::longValue),
done

2024-04-22 07:17 UTC, olperr1 approved these changes

2024-04-25 07:11 UTC, merged